networks:
  rabbitmq-network: {}

services:
  rabbitmq:
    image: rabbitmq:4.0
    hostname: my-rabbit-hostname
    container_name: my-rabbit-server
    networks:
      - rabbitmq-network
    restart: always
  my-rabbitmq-app:
    build: .
    container_name: my-rabbitmq-app
    networks:
      - rabbitmq-network
    depends_on:
      - rabbitmq
    volumes:
      - ./app:/app
      - /app/node_modules
    working_dir: /app
    command: tail -f /dev/null
